C_FILES = test_amb_packing.c ../../amb_packing/amb_packing.c ../../keccak256/keccak256.c ../../insertion_sort/insertion_sort.c

test_amb_packing: $(C_FILES)
	gcc -o test_amb_packing $(C_FILES) -std=c99
